rootProject.name = 'contract-bus-demo'

include 'base-contract'
include 'contract-bus'
include 'contract-bus-spring-boot-starter'
include 'market-data-contract'
include 'market-data-spring-boot-starter'
include 'analytics-contract'
include 'analytics-spring-boot-starter'
include 'analytics-restclient-starter'
include 'app'
